// <auto-generated />
namespace DVDLibraryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_ratingname_from_dvd_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_ratingname_from_dvd_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202110190234439_remove_ratingname_from_dvd_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
